#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
APP="$1"; PORT="$2"; IMAGE="app/$APP";

DOMAINS_FILE="$DOKKU_ROOT/$APP/DOMAINS"

id=$(docker run -d $IMAGE test -f app/DOMAINS)
if [ $(docker wait $id) -ne 0 ]; then
    echo "no domains file founded"
    exit 0
fi

echo "----> Domains file founded"
if [[ -f "$DOMAINS_FILE" ]]; then
  DOMAINS=$(< "$DOMAINS_FILE")
  dokku domains:set $APP $DOMAINS
fi
